### ISSUE TITLE
Remove sudo

### ISSUE THREAD

**Issue by grembo** [depenguin-me/mfsbsd-13.1-script#1]
Really cool script, just tested and it seems to work ok.

It would be good to remove sudo from the script (and maybe check for uid 0 on start)., sinceHetzner servers don't have sudo installed by default and one connects to servers running the rescue image using root anyway.

**Comment by bretton** [comment]
Thanks! Updated in 4b19fd4f701dad8e58568a27797d79f09607b1c8
