### ISSUE TITLE
qemu won't run on servers that don't have virtualization support

### ISSUE THREAD

**Issue by click0** [depenguin-me/mfsbsd-13.1-script#17]
Subj.
I have a server with an Intel Atom processor where there is no virtualization support.

Therefore, instead of the mandatory qemu options (  `-enable-kvm`  `-cpu host` ), you need to check for virtualization support.

**Comment by grembo** [comment]
Do you have a spec for that server?

The easiest way to handle this short term is probably to provide a command line option, but pull requests to detect it automatically are welcome.

**Comment by click0** [comment]
> Do you have a spec for that server?
> 
> The easiest way to handle this short term is probably to provide a command line option, but pull requests to detect it automatically are welcome.

There is a `kvm-ok` script for this.

I found this CPU:
`hw.model: Intel(R) Atom(TM) CPU N2800   @ 1.86GHz`

**Comment by grembo** [comment]
Ah, so assuming that kvm-ok is available b default, all that’s needed is

‘’’
if kvm-ok; then
  qemu_args+=(-enable-kvm -cpu host)
fi
’’’
?
