### ISSUE TITLE
Test request: Leaseweb Dedicated Servers

### ISSUE THREAD

**Issue by bretton** [depenguin-me/mfsbsd-13.1-script#45]
Test request: Leaseweb Dedicated Servers

https://www.leaseweb.com/dedicated-servers

Most options are dual drive.

They have a recovery console, with a FreeBSD image
https://kb.leaseweb.com/products/dedicated-server/starting-your-dedicated-server-in-rescue-mode

FreeBSD is listed as supported install image too
https://kb.leaseweb.com/products/dedicated-server/reinstalling-your-dedicated-server

**Comment by nkfilis** [comment]
FreeBSD is a pretty straightforward thing with Leaseweb. Their default FreeBSD installation is mostly single-disk UFS, but their rescue images are fairly recent, so installing a box from FreeBSD rescue works out of the box.

**Comment by bretton** [comment]
thanks @nkfilis will close as "will likely work" - valid test would be useful all the same
