### ISSUE TITLE
Add more than two drives?

### ISSUE THREAD

**Issue by lukas-at-harren** [depenguin-me/mfsbsd-13.1-script#49]
Hi,

I am currently bootstrapping a server with four drives, and the script always only selects /dev/sd[ab] and not /dev/sd[abcd] as its listed in `lsblk`.
I found there is a limitation that you can only add 4 drives to qemu, but if you use `if=virtio` more can be added.

What can be done about this, so that the installation can directly take care of all disks?

Kind regards.

**Comment by bretton** [comment]
Hi @lukas-at-harren, nice problem!

so if we can get qemu to pass in 4 drives, then editing `depenguin_settings.sh` to something like
```
conf_disks="ada0 ada1 ada2 ada4"   # or ada0 | or nvme0n1 | or nvme0n1 nvme1n1
conf_disktype="raid10"   # or raidz1 or mirror or stripe
```
should allow the `depenguin_bsdinstall.sh` to complete installation.

I'm not sure how we'll do it or test it yet.

**Comment by lukas-at-harren** [comment]
@bretton thanks, I will give those a try.

**Comment by bretton** [comment]
sorry I've overwritten the test.sh file with a new PR test, let me know if you need it again or if it worked

**Comment by lukas-at-harren** [comment]
@bretton my machine that I could play around with quite quickly had to move towards production. And I am OOM right now. Out of machines. The next box will come along, and I will have this to try.

If you want to close the issue for now, that is ok. I would re-open it once I get to it.
